version: '3.8'
services:
  app:
    env_file:
      - ".env"
    build: .
    ports:
      - "8080:8000"

    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules


networks:
  app:
    driver: bridge